### ISSUE TITLE
User-friendly display of MemberEvent

### ISSUE THREAD

**Issue by dtgay** [FOSSRIT/infoboard#8]
Currently, MemberEvents just display as... MemberEvents. Probably want to do something like "made X friends" or whatever MemberEvent relates to. Example:

`oddshocks made 3 MemberEvent this week.`

**Comment by Qalthos** [comment]
All the events are now implemented (except for DownloadEvent, but more in a bit), even ForkApplyEvent which I'm pretty sure no longer exists as a thing you can do. Pull and restart and the events should be fixed.

DownloadEvent is something I'm still unclear about. Should you notice it come up, open a new issue and try to get an example of something that triggers it.

**Comment by dtgay** [comment]
You got it.
